#!/bin/bash

ant jar javadoc coverage

svnurl=$(svn info|awk '/^URL/ {print $2}')

rm -rf dist/Absimpa
svn export -q "${svnurl}" dist/Absimpa
rm dist/Absimpa/publish
jarfile=$(/bin/ls -1rt dist/Absimpa-*.jar|tail -1)

if echo "$jarfile" | grep -q dirty; then
  echo "cannot publish dirty file, check in subversion first"
fi

version=$(echo $jarfile|sed -e 's/.*-\|[.]jar//g')
srctgz="dist/Absimpa-src-${version}.tar.gz"
tar cfz "$srctgz" -C dist Absimpa

t=gnuher.de:apache/pifpafpuf.de/Absimpa

ssh gnuher.de "mkdir -p apache/pifpafpuf.de/Absimpa/download"
scp "$jarfile" "$t/download"
scp "$srctgz" "$t/download"
rsync --delete -az dist/AbsimpaDoc/ "$t/AbsimpaDoc"
scp -r dist/covereport "$t"
